### ISSUE TITLE
Can't make Redstone work

### ISSUE THREAD

**Issue by emanuelfranklyn** [kikelkik/LiftReloaded#10]
I'm trying to make the Redstone functionality work, but when I power the button block, nothing happens. I activated the Redstone property in the configs, but the elevator only moves when a player presses the button manually, tested with players and entities.

**Comment by kikelkik** [comment]
You're right, it doesn't really work - I detected the mistake in my test setup.
After inspection of the mechanism I'm thinking of removing the redstone feature completely because of performance concerns: For each redstone wire/repeater/... on the server all adjacent of adjacent (neighbor of neighbor) blocks has to be checked for a Lift button because there is no way to only get indirectly powered blocks. 
In my eyes, thats way too many block checks where most cases are not intended to start a Lift. 

Instead, I can offer you to support Lift trigger by a pressure plate positioned on a base/floor block.

**Comment by emanuelfranklyn** [comment]
What about an lamp, would it be possible to check if a lamp is activated?

**Comment by kikelkik** [comment]
Similar effect: I suspect that 99,99% of al redstone lamps on a server are not lift-related. However, I'd have to consider each lamp could belong to a Lift => check 100% of lamps although I'm only interested in 0,01% of these lamps. 
The plugin does not save any Lift information, it simply checks for apporpriate block structures when a button is pushed.

**Comment by emanuelfranklyn** [comment]
Well, in that case I think it is better for the feature to be removed in order to preserve the server's tps
